# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftChat (iOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase'
  pod 'Firebase/Database'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Analytics'

  # Pods for SwiftChat (iOS)

end

target 'SwiftChat (macOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftChat (macOS)

end
